### ISSUE TITLE
Spike: Update Repo created with Template with new Template features

### ISSUE THREAD

**Issue by franTarkenton** [bcgov/nr-quickstart-typescript#250]
**As a** *user of the greenfield template* **I want** *be able to identify and consume updates to the greenfield template* **So That** *I can take advantage of new features to the greenfield template*

**Additional Context**
- User starts by creating a new repo that consume the greenfield template as a "template"
- How do I slurp in new features after the repo has been created
-Versioning of actions
-Versioning of greenfield template 
-Release notes when new features are released. 

**Acceptance Criteria**
- [ ] Documentation that describes how to identify differences and slurp them up into my repo

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by DerekRoberts** [comment]
Long since solved with Dependabot updating our GitHub Actions.  Symantic versioning and release notes to be used for Actions.
