### ISSUE TITLE
Use Vault and Rotating Secrets

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-quickstart-typescript#320]
Vault keys & secrets are encrypted inside Vault. It can provide better security than OpenShift secrets within your application if you use a secure workflow to consume the secrets.

Updated description by @mbystedt.
Initiated by @ConradBoydElliottGustafson and @rparfig.

**Comment by mbystedt** [comment]
I would modify the statement to: Vault keys & secrets are encrypted **inside Vault*. It can provide better security than OpenShift secrets within your application if you use a secure workflow to consume the secrets.

**Comment by DerekRoberts** [comment]
https://beta-docs.developer.gov.bc.ca/vault-secrets-management-service/

**Comment by DerekRoberts** [comment]
Being investigated first by Team Encora.  Blocked for now.  Sorry @webgismd!

**Comment by DerekRoberts** [comment]
Via Team Encora / @RMCampos:

`  retrieve-vault-token:
    name: Retrieve Vault Secrets
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Import Secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault-iit.apps.silver.devops.gov.bc.ca
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            apps/data/<path>/<here> <secret-key> | <env-var-name-1>;
            apps/data/<path>/<here> <secret-key> | Menv-var-name-2>;`

**Comment by RMCampos** [comment]
@DerekRoberts @mbystedt Thinking of reuse of this job, would be ideal to have something like a parameter or configuration to set how many secrets that repo needs. Maybe try a bash script?

**Comment by DerekRoberts** [comment]
@RMCampos Makes sense.  Let's do a meeting with working example and plan it?  I can likely write the Action next sprint.

**Comment by RMCampos** [comment]
Hey @DerekRoberts here's a full working job:

```
deploy-dev:
  name: DEV Deployment (Only PR)
  runs-on: ubuntu-latest
  env:
    ZONE: ${{ github.event.number }}
    NRBESTAPI_VERSION: snapshot-${{ github.event.number }}
  steps:
    - name: Import Secrets
      id: secrets
      uses: hashicorp/vault-action@v2
      with:
        url: https://vault-iit.apps.silver.devops.gov.bc.ca
        token: ${{ secrets.VAULT_TOKEN }}
        exportEnv: 'false'
        secrets: |
          apps/data/dev/spar/app-spar/db_proxy_read_only db_username | VAULT_DB_USER;
          apps/data/dev/spar/app-spar/db_proxy_read_only db_password | VAULT_DB_PASS;

    - uses: actions/checkout@v3
    - name: Deploy
      run: |
        # Login to OpenShift and select project
        oc login --token=${{ secrets.OC_TOKEN }} --server=${{ secrets.OC_SERVER }}
        oc project ${{ secrets.OC_NAMESPACE }}

        # Clean previous image, if rebuilding
        if [ ${{ needs.build-service-api.outputs.build == 'true' }} ]
        then
          # Clear stale images for import/replacement
          oc delete is ${{ env.NAME }}-${{ env.ZONE }}-service-api || \
            echo "No previously imported images have been found"
        fi

        # Process and apply template
        oc process -f .github/openshift/deploy.backend.yml -p ZONE=${{ env.ZONE }} \
          -p DATABASE_USER=${{ steps.secrets.outputs.VAULT_DB_USER }} \
          -p DATABASE_PASSWORD=${{ steps.secrets.outputs.VAULT_DB_PASS }} \
          -p PROMOTE=${{ github.repository }}:${{ env.ZONE }}-service-api | oc apply -f -

        # Follow any active rollouts (see deploymentconfigs)
        oc rollout status dc/${{ env.NAME }}-${{ env.ZONE }}-service-api -w
```

**Comment by DerekRoberts** [comment]
Well solved by @RMCampos !  Ticket being closed, can be revisited if worked into QuickStart.
