### ISSUE TITLE
Spike: investigate API gateway

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-quickstart-typescript#632]
Team Alliance has docs and working examples.

https://github.com/bcgov/nr-forest-client-api/blob/257b801c77643dbde1d24870fd247af5acb32b4e/.github/workflows/merge-main.yml#L316

**Comment by DerekRoberts** [comment]
https://github.com/bcgov/nr-forest-client-api/blob/main/.github/workflows/merge-main.yml#L313

https://github.com/bcgov/nr-forest-client-api/wiki/Config-API-Services-Portal

https://bcgov.github.io/aps-infra-platform/guides/owner-journey/

**Comment by DerekRoberts** [comment]
There's not enough code to make an Action worthwhile at the moment.  Maybe in a future pass we can figure out more value and how to ease the setup steps?

**Comment by webgismd** [comment]
for setting up the entries in the API Gateway, and in turn the BC Data Catalogue.. it would be good to be able to capture what was done manually and convert it to a pipeline.. if possible.. it may be overkill though.. as this may not be done often.. but it would be good to capture those configs as codes.
